docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_JAVA_VERSION
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker version
    - docker buildx create --use
    - docker buildx build --push --build-arg="JAVA_VERSION=$CI_JAVA_VERSION" --platform linux/amd64,linux/arm64 --build-arg="ZULU_VERSION=$CI_ZULU_VERSION" --tag $DOCKER_IMAGE_NAME .
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'main'
