name: Build to Docker Hub (multi-arch)

env:
  PLATFORMS: linux/amd64,linux/arm64
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      java_version:
        description: "JAVA_VERSION para build-arg (e.g., 21.0.8, 17.0.6, 15)"
        required: false
        default: "21.0.8"
      zulu_version:
        description: "ZULU_VERSION (e.g., zulu21, zulu17). Si vacío, tu Dockerfile puede calcularlo."
        required: false
        default: "zulu21"

jobs:
  build:
    name: Build - ${{matrix.jvm_type}}
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
     matrix:
        jvm_type: [ jdk, jre ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve inputs/defaults
        id: vars
        run: |
          echo "JAVA_VERSION=${{ github.event.inputs.java_version || '21.0.8' }}" >> $GITHUB_OUTPUT
          echo "ZULU_VERSION=${{ github.event.inputs.zulu_version || 'zulu21' }}" >> $GITHUB_OUTPUT
