name: Docker Build to Docker Hub (multi-arch)

env:
  PLATFORMS: linux/amd64,linux/arm64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      java_version:
        description: "JAVA_VERSION para el build-arg"
        required: false
        default: "21.0.8"
      zulu_version:
        description: "ZULU_VERSION para el build-arg (zulu17, zulu21, etc.)"
        required: false
        default: "zulu21"
      image_repo:
        description: "Repositorio en Docker Hub (usuario/repo)"
        required: false
        default: "tuusuario/zulu-java-alpine"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
